### ISSUE TITLE
Fx 5 compat

### ISSUE THREAD

**Issue by fbender** [hail2u/reload-tab-on-double-click#1]
I can't update to Fx 5 (beta) without this extension – please update it :).

**Comment by hail2u** [comment]
I don't want to check my Firefox add-ons are compatible with beta or alpha, Aurora by my hand.

You can install, check add-on and report add-on's compatibility with [Add-on Compatibility Reporter](https://addons.mozilla.org/en-US/firefox/addon/add-on-compatibility-reporter/).
