### ISSUE TITLE
build as Jetpack (no restart extension)

### ISSUE THREAD

**Issue by fbender** [hail2u/reload-tab-on-double-click#2]
I'm not sure, but it looks like you can implement this extension as a Jetpack extension, so no restart is required when installing the extension (and it might improve performance). Please take a look at https://jetpack.mozillalabs.com/.

**Comment by hail2u** [comment]
Your suggestion is worth considering.

**Comment by hail2u** [comment]
I give up to maintain Firefox extensions.
